"""Add a title field to feed entries.

Revision ID: 18bd14dd0a8
Revises: 2d54ac2259e
Create Date: 2015-11-17 14:43:07.422699

"""

# revision identifiers, used by Alembic.
revision = '18bd14dd0a8'
down_revision = '2d54ac2259e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('feed_title', sa.String(length=2400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'feed_title')
    ### end Alembic commands ###
