"""empty message

Revision ID: 4d2bce58c62
Revises: 3bc79eac35a
Create Date: 2015-11-11 16:25:48.466828

"""

# revision identifiers, used by Alembic.
revision = '4d2bce58c62'
down_revision = '3bc79eac35a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
